### ISSUE TITLE
TT From DOP and pin diameter - Helical gear

### ISSUE THREAD

**Issue by RossMarley17** [Precision-Technologies-Ltd/master-gauge-issues#10]
![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146433489/7aa4a6a6-366e-4427-b9d7-0f9cd95938e8)

Hi Simon
I have inputted 34 teeth, 2.3630 module, 21° pressure angle and 25° helix angle.

 I then try to find tooth thickness from distance over pins and pin diameter and put the pin diameter as 4.75 and dop as 98.6233. I am getting 3.6882 but on the other computer it is 4.6262 

Thanks

**Comment by inyoka** [comment]
Hi, is this using Function 8 on the INVHEL program?  

Currently I am getting the same result on both apps...
![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/52d61cb9-b496-4f91-adb7-fe5b35b1cde7)

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/077855b7-bc92-4994-887d-3ab0c02af817)

**Comment by RossMarley17** [comment]
Hi simon

It is correct it was my mistake i put two different figures in. I put 98.6233 in the computer before and i was getting 4.6267. I then put a different figure in this calculator 96.6233 instead of 98.6233. - Its been a long day. This program gives me the same tt as the computer when i compare properly. This issue can be closed and sorry for wasting your time

**Comment by inyoka** [comment]
No problem at all.  I'd rather get too many bug reports than too few.
