### ISSUE TITLE
DBP from DBP, Pin Dia & New Pin Dia

### ISSUE THREAD

**Issue by JB-1956** [Precision-Technologies-Ltd/master-gauge-issues#12]
Hi Simon,

Customer DBP:
Pin Ø4.016
DBP: 31.5041 / 31.4282

Need to calculate an alternative pin for Production:
Pin Ø: 4.0
DBP: 31.7371 / 31.6633

The program has come up with an error please see screen shot attached,

Thanks
Jamie

![2 DBP](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146351525/6bd1f735-ebcc-4317-9bd3-5672ba74d4f7)

**Comment by inyoka** [comment]
Thanks Jamie, I'll take a look.

**Comment by inyoka** [comment]
Hi Jamie, Just to confirm this internal calculation and has been fixed.  

There was an error on the external form as well.  This has also been fixed to display a Below BCD error.  

All future builds (greater than version 0.99.175) will include this fix.

Thank you for the bug report.

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/b6b42a0f-1fb4-41db-950b-eb1cbb78a94a)

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/cc8f8422-7015-4add-91d5-bc6d8c775d90)
