### ISSUE TITLE
DBP from DBP, Pin Dia and new pin dia

### ISSUE THREAD

**Issue by RossMarley17** [Precision-Technologies-Ltd/master-gauge-issues#13]
When i input the data below i get a warning saying new pin size cannot be zero even though i entered 0.900.
When i put this information in on the computer in the drawing office i get 18.73 as the new size

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146433489/754cab8b-f19d-4879-a739-a2afa7c922ac)

**Comment by inyoka** [comment]
This is now fixed.  Hopefully a new version will be rolled out soon ...

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/55882395-5c7d-4f00-8f34-c5eeb64bfdbc)
