### ISSUE TITLE
Span Size Error

### ISSUE THREAD

**Issue by JB-1956** [Precision-Technologies-Ltd/master-gauge-issues#14]
HI Simon,

Gear Details:

T: 26
Mod: 2.5
PA: 25°

TT: 3.8119
Span Size Calculated: 26.7836 Across 4 Teeth

This span size calculated by the program is larger than the finished span size on the drawing, this highlighted the error as the TT inputted was from a component that had gone undersize.

Correct Data from Old Program:

TT: 3.8119
Span Size Calculated: 26.575

![Span Size Error](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146351525/b7b0c2fa-7b84-4f0b-bd37-ccc8b1468245)

**Comment by inyoka** [comment]
Thanks for the bug report, I have fixed the issue in all versions greater than v240220. 

However, in light of this I am not confident in the Helical calculations and will create a separate bug report to create additional tests around this issue.  Please be aware of this if anyone uses the helical calcs.

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/5df7f2c3-78d5-42f6-bb70-5ed715a5e4bc)

**Comment by inyoka** [comment]
Will now calculate number of teeth if value set to zero :

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/b9e8ce7c-501a-4952-a358-aa5c78f0f0de)
