### ISSUE TITLE
Radius over pin

### ISSUE THREAD

**Issue by RossMarley17** [Precision-Technologies-Ltd/master-gauge-issues#16]
Hi Simon

Hope you are well, i am calculating the dimension over pins for an odd number of teeth, the program has stopped giving me a ROP. Please see below. For a Odd number of teeth helix. With the old computer it gives me an ROP of 39.3165 
![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146433489/c250e649-141b-4f67-bf89-a797288e1ce3)

**Comment by inyoka** [comment]
Okay I'll take a look at it and get back to you.

**Comment by JB-1956** [comment]
Hi Simon,

Just a quick one, had this happen with mine also.

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146351525/2679cd02-9837-4bce-8ffe-54632c2bb077)

ROP calculated form the old program was: 66.9156 using a Ø4.5mm Pin.

Thanks
Jamie

**Comment by inyoka** [comment]
Ok @RossMarley17 @JB-1956 this seems to be working, the fix will be in the next rollout, sorry for the delay. 

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/c9332c32-36b4-4cb5-972e-50f412c4b640)
![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/98422317-4391-4563-8db2-9f09eb7a129d)
