### ISSUE TITLE
TT at Any Diameter

### ISSUE THREAD

**Issue by RossMarley17** [Precision-Technologies-Ltd/master-gauge-issues#5]
![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146433489/78a1f043-1c14-4a37-8c5d-18dab23cc36b)

I inputted a spur gear into the TT at any diameter, the new tooth thickness I got was correct for the diameter I required (36), however it has pulled though the 36 diameter I required in the new helix angle output. This is saying 36 but it is a spur gear so should be 0 still.

Also new Gap is showing 0.000 whereas on the helical program on the computer it is giving me a new gap of 4.5308mm

**Comment by inyoka** [comment]
Great thank you.  I'll look into this now.

**Comment by inyoka** [comment]
This has now been fixed and will be available in the next version.

Thank you @RossMarley17 

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/da91cd14-ba57-4390-a52e-3bf4c7aed683)
