### ISSUE TITLE
Major Diameter Calibration

### ISSUE THREAD

**Issue by PatrickWalkerPTI** [Precision-Technologies-Ltd/master-gauge-issues#6]
Worked for the first spur gear calculation but didn't work for the example below.

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/123367097/4dff0dae-35c6-4a02-86fb-c6dd7a57d63d)

**Comment by inyoka** [comment]
Working ...

https://github.com/Precision-Technologies-Ltd/master-gauge/commit/c9682abbde8f137cb8237d6b4aeec8349031d4d6

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/537ba3e8-c59e-4b69-8a73-af486d3c0909)
