### ISSUE TITLE
Major Diameter Calibration Layout

### ISSUE THREAD

**Issue by PatrickWalkerPTI** [Precision-Technologies-Ltd/master-gauge-issues#7]
Can we make the following changes

Change the word "Pinsize" to "Pin Dia" in 2 places.

Align "Tooth Thickness" text box with "Dimension Over Pins" text box
Align "Actual Tooth Thickness" text box with "Actual DOP" text box and relabel text box as Actual Dimension Over Pins"
Align "Corrected Major Dia" with "Nominal Major Dia"

**Comment by inyoka** [comment]
Pinsize has been changed to Pin Dia in two place.

**Nominal** and **Corrected Major Dia** are aligned.
**Dimension Over Pins** and **Tooth Thickness** are aligned.
**Actual Dimension Over Pins** and **Actual Tooth Thickness** are aligned.


![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/c37f6a46-27f1-48b1-a5e3-e07d85a2dd30)
